/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Model.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/Model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1366} decay={2} position={[-1.701, 7.049, -1.602]} rotation={[-1.806, -0.308, -2.24]} target={nodes['TriLamp-Back001'].target}>
        <primitive object={nodes['TriLamp-Back001'].target} position={[0, 0, -1]} />
      </directionalLight>
      <directionalLight intensity={2049} decay={2} position={[-7.233, 7.207, 4.936]} rotation={[-0.868, -0.723, -0.663]} target={nodes['TriLamp-Back002'].target}>
        <primitive object={nodes['TriLamp-Back002'].target} position={[0, 0, -1]} />
      </directionalLight>
      <pointLight intensity={10870.283} decay={2} position={[4.171, 2.808, -0.496]} rotation={[-2.25, 0.727, 2.453]} />
      <pointLight intensity={10870.283} decay={2} position={[-0.486, 3.889, -0.576]} rotation={[-2.25, 0.727, 2.453]} />
      <pointLight intensity={5435.141} decay={2} position={[0.811, 0.701, 0.45]} rotation={[-0.388, 0.413, 0.162]} />
      <pointLight intensity={5435.141} decay={2} position={[-1.672, 0.701, 0.45]} rotation={[-0.388, -0.734, -0.267]} />
      <pointLight intensity={5435.141} decay={2} color="#ff9d00" position={[4.654, 3.717, -3.401]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={5435.141} decay={2} color="#ff9d00" position={[4.997, 3.717, -3.401]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={5435.141} decay={2} color="#ff9d00" position={[-5.577, 3.717, -3.401]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={5435.141} decay={2} color="#ff9d00" position={[-5.234, 3.717, -3.401]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.dull_mat} position={[-0.464, 1.233, -0.016]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.464, 1.271, -3.954]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.golden} position={[-0.463, 1.359, -0.017]} />
      <group position={[-0.418, 0.694, 0.001]} scale={[0.683, 0.594, 0.6]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.golden} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.dull_mat} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.bg} position={[-0.24, 0, -1.845]} scale={[-4.634, -8.614, -1.223]} />
      <group position={[2.329, 0.013, -0.831]} scale={0.018}>
        <mesh geometry={nodes.meshChair.geometry} material={materials.dull_mat} />
        <mesh geometry={nodes.meshChair_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.meshChair_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[3.746, 0.013, 0.012]} rotation={[0, -1.571, 0]} scale={0.018}>
        <mesh geometry={nodes.meshChair002.geometry} material={materials.dull_mat} />
        <mesh geometry={nodes.meshChair002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.meshChair002_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-4.642, 0.013, 0.012]} rotation={[0, 1.571, 0]} scale={0.018}>
        <mesh geometry={nodes.meshChair001.geometry} material={materials.dull_mat} />
        <mesh geometry={nodes.meshChair001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.meshChair001_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-0.472, 1.381, 0]} scale={0.026}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials.candle_holder} />
        <mesh geometry={nodes.Mesh002_2.geometry} material={materials.dull_mat} />
      </group>
      <group position={[0.953, 1.381, 0]} scale={0.026}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.candle_holder} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials.dull_mat} />
      </group>
      <group position={[-1.907, 1.381, 0]} scale={0.026}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.candle_holder} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials.dull_mat} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials.bg} position={[-0.24, -0.084, 0.269]} scale={[-4.653, -5.979, -2.552]} />
      <group position={[-0.289, 3.774, -3.656]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.035, 0.035, 0.044]}>
        <mesh geometry={nodes.lamp_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.lamp_2.geometry} material={materials['black metal']} />
        <mesh geometry={nodes.lamp_3.geometry} material={materials['GOld metal']} />
        <mesh geometry={nodes.lamp_4.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.lamp_5.geometry} material={materials.clearMarble} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.dull_mat} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.004']} morphTargetDictionary={nodes.Plane002.morphTargetDictionary} morphTargetInfluences={nodes.Plane002.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/Model.glb')
